apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "springboot-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    serviceAccountkubernetes.io/service-account.name: {{ include "springboot-chart.fullname" . | quote }}
    pillar: {{ .Values.envOverrides.pillar }}
